openapi: 3.0.0
info:
  title: documentation for the delivery made by the farmer
  version: 1.0.0
  description: covers simple test for farmer's delivery
paths: 
  /api/v1/agentDelivery/createDelivery/{vehhicleId}:
    post:
      summary: This endpoint is to create the delivery for the agent's Farmer using the vehicle that the driver has listed
      parameters:
        - in: path
          name: vehhicleId
      tags: [Agent]
      security: 
        - bearerAuth: []
      requestBody:
        required: true
        content: 
          application/json:
            schema:
              type: object
              required: 
                - agentFarmerId
                - produceType
                - quantity
                - pickupLocation
                - Destination
                - customersDetails
                - customersName
              properties:
                agentFarmerId:
                  type: string
                  example: 6a2d8938b7543a8e12cd175a
                produceType:
                  type: string
                  example: watermelon
                quantity:
                  type: string
                  example: 500kg
                pickupLocation:
                  type: string 
                  example: Ikorodu, Lagos
                Destination:
                  type: string
                  example: Mile 12 Market, Lagos
                customersDetails:
                  type: string
                  example: 08034201969
                customersName:
                  type: string
                  example: Taiwo Kehinde           
      responses:
        "200":
          description: Agents farmers delivery has been requested 

  /api/v1/agentDelivery/acceptDelivery/{deliveryId}:
    patch:
      summary: this endpoint is for the driver to accept the delivery of the agent with the delivery's ID in the params and the driver is logged in
      parameters:
        - in: path
          name: deliveryId
      tags: [Driver]
      security: 
        - bearerAuth: []
      responses:
        "200":
          description: Agents farmers delivery has been accepted by a driver.

  /api/v1/agentDelivery/completeDelivery/{deliveryId}:
    post:
      summary: This endpoint completes the delivery by the driver by inputing his pin
      parameters:
        - in: path
          name: deliveryId
      tags: [Driver]
      security: 
        - bearerAuth: []
      requestBody:
        required: true
        content: 
          application/json:
            schema:
              type: object
              required: 
                - PIN
              properties:
                PIN:
                  type: string
                  example: 1234              
      responses:
        "200":
          description: Agents farmers delivery has been completed   
  
  /api/v1/agent/createAgentFarmer:
    post:
      summary: this end point is to create the the agent Farmer
      tags: [Agent]
      security: 
        - bearerAuth: []
      requestBody:
        required: true
        content: 
          application/json:
            schema:
              type: object
              required: 
                - farmerFullName
                - phoneNumber
                - farmLocation
                - mainProduceType
              properties:
                farmerFullName:
                  type: string
                  example: Ifeoma Kelechi
                phoneNumber:
                  type: string
                  example: 08032401923
                farmLocation:
                  type: string
                  example: Ikorodu lagos
                mainProduceType:
                  type: string
                  example: tomatoes                        
      responses:
        "200":
          description: Agents farmers created successfully


    

  