openapi: 3.0.0
info:
  title: documentation for the user's bank
  version: 1.0.0
  description: covers simple test for user's bank
paths: 
  /api/v1/bank/createBank:
    post:
      summary: this endpoint is to add the bank to the user, be it agent, farmer or driver
      tags: [add bank for user]
      security: 
        - bearerAuth: []
      requestBody:
        required: true
        content: 
          application/json:
            schema:
              type: object
              required: 
                - bankName
                - AccountName
                - AccountNumber
              properties:
                bankName:
                  type: string
                  example: Eco Bank
                AccountName:
                  type: string
                  example: Philip Ekong
                AccountNumber:
                  type: string
                  example: 89882339328923                  
      responses:
        "201":
          description: user's bank successfully added    

  /api/v1/payment/withdraw:
    post:
      summary: this endpoint is to withdraw money from your wallet, you can use a real account number
      tags: [withdraw]
      security: 
        - bearerAuth: []
      requestBody:
        required: true
        content: 
          application/json:
            schema:
              type: object
              required: 
                - amount
                - accountNumber
                - bankName
              properties:
                amount:
                  type: number
                  example: 1000
                accountNumber:
                  type: string
                  example: 0123456789         
                bankName:
                  type: string
                  example: Access Bank          
      responses:
        "201":
          description: user's has withdrawn successfully     

  