openapi: 3.0.0
info:
  title: documentation for the delivery made by the farmer
  version: 1.0.0
  description: covers simple test for farmer's delivery
paths: 
  /api/v1/delivery/createDelivery/{vehhicleId}:
    post:
      summary: create the delivery for the farmer using the vehicle that the driver has listed
      parameters:
        - in: path
          name: vehhicleId
      tags: [Create delivery for the farmer]
      security: 
        - bearerAuth: []
      requestBody:
        required: true
        content: 
          application/json:
            schema:
              type: object
              required: 
                - productType
                - quantity
                - weight
                - AddressOrpickUpLocation
                - landMarkToAddressForPickup
                - Destination
                - customersPhoneNumber
                - CustomersOtherNumber
                - vehicleType
              properties:
                productType:
                  type: string
                  example: watermelon
                quantity:
                  type: string
                  example: 5
                weight:
                  type: string
                  enum: 
                    - Kg
                    - Tons
                    - Bags
                  default: Kg
                AddressOrpickUpLocation:
                  type: string 
                  example: Ikorodu, Lagos
                landMarkToAddressForPickup:
                  type: string
                  example: caleb university
                Destination:
                  type: string
                  example: Mile 12 Market, Lagos
                customersPhoneNumber:
                  type: string
                  example: 08034201969
                CustomersOtherNumber:
                  type: string
                  example: 08033858575
                vehicleType:
                  type: string
                  example: 6a26be437850290aa292bb55                
      responses:
        "201":
          description: farmers delivery has been requested 

  /api/v1/delivery/accept-Delivery/{deliveryId}:
    patch:
      summary: this endpoint is for the driver to accept the delivery with the delivery's ID in the params and the driver is logged in
      parameters:
        - in: path
          name: deliveryId
      tags: [Accept Delivery by driver]
      security: 
        - bearerAuth: []
      responses:
        "201":
          description: farmers delivery has been accepted by a driver.

  /api/v1/delivery/completeDelivery/{deliveryId}:
    post:
      summary: create the delivery for the farmer using the vehicle that the driver has listed
      parameters:
        - in: path
          name: deliveryId
      tags: [Complete delivery]
      security: 
        - bearerAuth: []
      requestBody:
        required: true
        content: 
          application/json:
            schema:
              type: object
              required: 
                - PIN
              properties:
                PIN:
                  type: string
                  example: 1234              
      responses:
        "201":
          description: delivery has been completed   

    

  